const mongoose = require('mongoose');
require('dotenv').config({ path: '.env.local' });

const tourSchema = new mongoose.Schema(
  {
    id: { type: String, required: true, unique: true },
    title: { type: String, required: true },
    destination: { type: String, required: true },
    country: { type: String, required: true },
    duration: { type: String, required: true },
    daysCount: { type: Number, required: true },
    price: { type: Number, required: true },
    originalPrice: { type: Number, required: true },
    rating: { type: Number, default: 4.5 },
    reviews: { type: Number, default: 0 },
    mainImage: { type: String, required: true },
    galleryImages: [String],
    category: { type: String, enum: ['leisure', 'mice'], required: true },
    tags: [String],
    description: String,
    overview: String,
    highlights: [String],
    inclusions: [String],
    exclusions: [String],
    itinerary: [
      {
        day: Number,
        title: String,
        description: String,
        activities: [String],
        meals: { breakfast: Boolean, lunch: Boolean, dinner: Boolean },
        accommodation: String,
      },
    ],
    priceBreakdown: mongoose.Schema.Types.Mixed,
    groupSize: { min: Number, max: Number },
    bestTimeToVisit: String,
    difficulty: { type: String, enum: ['Easy', 'Moderate', 'Challenging'] },
    departureDates: [String],
    testimonials: [
      {
        name: String,
        location: String,
        rating: Number,
        review: String,
        avatar: String,
      },
    ],
    importantNotes: [String],
    cancellationPolicy: String,
    isActive: { type: Boolean, default: true },
  },
  { timestamps: true }
);

const Tour = mongoose.model('Tour', tourSchema);

const toursData = [
  {
    id: '1',
    title: 'Bali Beach Paradise',
    destination: 'Bali',
    country: 'Indonesia',
    duration: '5 Days / 4 Nights',
    daysCount: 5,
    price: 45000,
    originalPrice: 65000,
    rating: 4.8,
    reviews: 245,
    mainImage: 'https://images.unsplash.com/photo-1537225228614-b6b0e5b002ea?w=1400&h=700&fit=crop',
    galleryImages: [
      'https://images.unsplash.com/photo-1537225228614-b6b0e5b002ea?w=600&h=400&fit=crop',
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&h=400&fit=crop',
      'https://images.unsplash.com/photo-1489749798305-4fea3ba63d60?w=600&h=400&fit=crop',
    ],
    category: 'leisure',
    tags: ['Offbeat', 'Beach', 'International', 'Romantic'],
    description: 'Experience the tropical beauty of Bali with pristine beaches, ancient temples, and vibrant culture.',
    overview: 'Escape to paradise and discover pristine beaches, ancient temples, and vibrant culture.',
    highlights: [
      'Relax on pristine white sand beaches',
      'Visit the iconic Tanah Lot Temple',
      'Explore traditional Balinese villages',
      'Experience authentic Balinese cuisine',
    ],
    inclusions: [
      'Round-trip flights',
      'Hotel accommodation',
      'Daily breakfast',
      'Airport transfers',
    ],
    exclusions: [
      'Personal expenses',
      'Visa fees',
      'Meals not specified',
    ],
    itinerary: [
      {
        day: 1,
        title: 'Arrival in Bali',
        description: 'Arrive and transfer to hotel',
        activities: ['Airport arrival', 'Hotel check-in'],
        meals: { lunch: true, dinner: true },
        accommodation: 'Hotel in Seminyak',
      },
      {
        day: 2,
        title: 'Beach Relaxation',
        description: 'Relax at beautiful beaches',
        activities: ['Beach time', 'Temple visit'],
        meals: { breakfast: true, lunch: true, dinner: true },
        accommodation: 'Hotel in Seminyak',
      },
      {
        day: 3,
        title: 'Culture & Village',
        description: 'Explore local culture',
        activities: ['Market tour', 'Rice terrace walk'],
        meals: { breakfast: true, lunch: true, dinner: true },
        accommodation: 'Hotel in Ubud',
      },
      {
        day: 4,
        title: 'Water Sports',
        description: 'Adventure activities',
        activities: ['Surfing', 'Snorkeling'],
        meals: { breakfast: true, lunch: true, dinner: true },
        accommodation: 'Hotel in Seminyak',
      },
      {
        day: 5,
        title: 'Departure',
        description: 'Return home',
        activities: ['Breakfast', 'Shopping', 'Departure'],
        meals: { breakfast: true, lunch: true },
        accommodation: 'N/A',
      },
    ],
    priceBreakdown: {
      'Flights': 15000,
      'Hotel': 16000,
      'Meals': 8000,
      'Activities': 4000,
      'Transfers': 2000,
    },
    groupSize: { min: 2, max: 20 },
    bestTimeToVisit: 'April to October',
    difficulty: 'Easy',
    departureDates: ['15th July 2024', '22nd July 2024', '29th July 2024'],
    testimonials: [
      {
        name: 'Priya Sharma',
        location: 'Mumbai',
        rating: 5,
        review: 'Amazing experience!',
        avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop',
      },
    ],
    importantNotes: [
      'Passport valid for 6 months',
      'Travel insurance recommended',
      'Pack light clothes',
    ],
    cancellationPolicy: 'Free cancellation until 30 days before travel',
    isActive: true,
  },
  {
    id: '2',
    title: 'Swiss Alps Adventure',
    destination: 'Switzerland',
    country: 'Europe',
    duration: '7 Days / 6 Nights',
    daysCount: 7,
    price: 85000,
    originalPrice: 120000,
    rating: 4.9,
    reviews: 312,
    mainImage: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1400&h=700&fit=crop',
    galleryImages: [
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&h=400&fit=crop',
      'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=600&h=400&fit=crop',
    ],
    category: 'leisure',
    tags: ['Adventure', 'Mountain', 'Trekking'],
    description: 'Explore majestic mountains with stunning views',
    overview: 'Experience the breathtaking beauty of Swiss Alps',
    highlights: ['Alpine hikes', 'Scenic railways', 'Mountain villages'],
    inclusions: ['Flights', 'Hotels', 'Meals', 'Tours'],
    exclusions: ['Tips', 'Personal expenses'],
    itinerary: [
      {
        day: 1,
        title: 'Zurich Arrival',
        description: 'Arrive in Zurich',
        activities: ['Airport pickup', 'Hotel check-in'],
        meals: { lunch: true, dinner: true },
        accommodation: 'Hotel in Zurich',
      },
    ],
    priceBreakdown: {
      'Flights': 28000,
      'Hotel': 36000,
      'Meals': 12000,
      'Transport': 6000,
      'Activities': 3000,
    },
    groupSize: { min: 2, max: 18 },
    bestTimeToVisit: 'June to September',
    difficulty: 'Moderate',
    departureDates: ['10th July 2024', '20th July 2024'],
    testimonials: [
      {
        name: 'Vikram Patel',
        location: 'Ahmedabad',
        rating: 5,
        review: 'Beyond words!',
        avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop',
      },
    ],
    importantNotes: ['Hiking boots required', 'Weather can change'],
    cancellationPolicy: 'Free cancellation until 45 days',
    isActive: true,
  },
  {
    id: '3',
    title: 'Egypt Ancient Wonders',
    destination: 'Egypt',
    country: 'Africa',
    duration: '6 Days / 5 Nights',
    daysCount: 6,
    price: 55000,
    originalPrice: 75000,
    rating: 4.7,
    reviews: 189,
    mainImage: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=1400&h=700&fit=crop',
    galleryImages: [
      'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=600&h=400&fit=crop',
    ],
    category: 'leisure',
    tags: ['Historical', 'Cultural'],
    description: 'Discover ancient mysteries',
    overview: 'Journey through time in Egypt',
    highlights: ['Pyramids', 'Nile Cruise', 'Temples'],
    inclusions: ['Flights', 'Cruise', 'Hotels'],
    exclusions: ['Visa', 'Tips'],
    itinerary: [
      {
        day: 1,
        title: 'Cairo Arrival',
        description: 'Arrive in Cairo',
        activities: ['Hotel check-in'],
        meals: { lunch: true, dinner: true },
        accommodation: 'Hotel in Cairo',
      },
    ],
    priceBreakdown: {
      'Flights': 18000,
      'Hotel': 22000,
      'Meals': 7000,
      'Tours': 6000,
      'Transport': 2000,
    },
    groupSize: { min: 2, max: 25 },
    bestTimeToVisit: 'October to April',
    difficulty: 'Easy',
    departureDates: ['5th October 2024'],
    testimonials: [],
    importantNotes: ['Visa required'],
    cancellationPolicy: 'Free cancellation until 40 days',
    isActive: true,
  },
  {
    id: '4',
    title: 'Paris Romance Tour',
    destination: 'Paris',
    country: 'France',
    duration: '4 Days / 3 Nights',
    daysCount: 4,
    price: 65000,
    originalPrice: 90000,
    rating: 4.9,
    reviews: 428,
    mainImage: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=1400&h=700&fit=crop',
    galleryImages: [],
    category: 'leisure',
    tags: ['Romantic', 'City'],
    description: 'Experience the city of love',
    overview: 'Romantic getaway in Paris',
    highlights: ['Eiffel Tower', 'Louvre', 'Seine Cruise'],
    inclusions: ['Flights', 'Hotels'],
    exclusions: ['Meals'],
    itinerary: [],
    priceBreakdown: {
      'Flights': 22000,
      'Hotel': 24000,
      'Tours': 6000,
      'Transport': 3000,
      'Meals': 10000,
    },
    groupSize: { min: 2, max: 12 },
    bestTimeToVisit: 'April to June',
    difficulty: 'Easy',
    departureDates: ['14th February 2025'],
    testimonials: [],
    importantNotes: ['Visa required'],
    cancellationPolicy: 'Free cancellation until 35 days',
    isActive: true,
  },
  {
    id: '5',
    title: 'Maldives Tropical Escape',
    destination: 'Maldives',
    country: 'Indian Ocean',
    duration: '5 Days / 4 Nights',
    daysCount: 5,
    price: 68000,
    originalPrice: 95000,
    rating: 4.9,
    reviews: 356,
    mainImage: 'https://images.unsplash.com/photo-1514282401047-7e6e5d71add8?w=1400&h=700&fit=crop',
    galleryImages: [],
    category: 'leisure',
    tags: ['Beach', 'Luxury', 'Honeymoon'],
    description: 'Paradise in Indian Ocean',
    overview: 'Luxury tropical escape',
    highlights: ['Overwater bungalows', 'Snorkeling', 'Spa'],
    inclusions: ['Flights', 'Resort', 'Meals'],
    exclusions: ['Beverages'],
    itinerary: [],
    priceBreakdown: {
      'Flights': 22000,
      'Resort': 32000,
      'Meals': 8000,
      'Activities': 4000,
      'Transfers': 2000,
    },
    groupSize: { min: 2, max: 10 },
    bestTimeToVisit: 'November to April',
    difficulty: 'Easy',
    departureDates: ['25th December 2024'],
    testimonials: [],
    importantNotes: ['No visa needed'],
    cancellationPolicy: 'Free cancellation until 45 days',
    isActive: true,
  },
  {
    id: '6',
    title: 'Tokyo Tech & Culture',
    destination: 'Tokyo',
    country: 'Japan',
    duration: '5 Days / 4 Nights',
    daysCount: 5,
    price: 54000,
    originalPrice: 75000,
    rating: 4.8,
    reviews: 267,
    mainImage: 'https://images.unsplash.com/photo-1540959375944-7049f642e9d4?w=1400&h=700&fit=crop',
    galleryImages: [],
    category: 'leisure',
    tags: ['Cultural', 'City', 'Technology'],
    description: 'Modern meets ancient',
    overview: 'Tokyo adventure',
    highlights: ['Temples', 'Markets', 'Technology'],
    inclusions: ['Flights', 'Hotels'],
    exclusions: ['Meals'],
    itinerary: [],
    priceBreakdown: {
      'Flights': 18000,
      'Hotel': 18000,
      'Meals': 8000,
      'Transport': 5000,
      'Activities': 5000,
    },
    groupSize: { min: 2, max: 16 },
    bestTimeToVisit: 'March to May',
    difficulty: 'Easy',
    departureDates: ['1st March 2025'],
    testimonials: [],
    importantNotes: ['Visa required'],
    cancellationPolicy: 'Free cancellation until 40 days',
    isActive: true,
  },
];

async function seedTours() {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('✅ Connected to MongoDB');

    // Clear existing tours
    await Tour.deleteMany({});
    console.log('🗑️ Cleared existing tours');

    // Insert tours
    const result = await Tour.insertMany(toursData);
    console.log(`✅ ${result.length} tours inserted successfully`);

    console.log('\n📋 Tours added:');
    result.forEach(tour => {
      console.log(`  - ${tour.title} (${tour.destination})`);
    });

    await mongoose.disconnect();
    process.exit(0);
  } catch (error) {
    console.error('❌ Error seeding tours:', error.message);
    process.exit(1);
  }
}

seedTours();